name: Tenable IaC Scan Workflow

on:
  push:
    branches:
      - main  # Trigger scan when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger scan on PRs targeting 'main'
  workflow_dispatch:  # This allows manual triggering of the workflow from the UI

jobs:
  ermetic-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code in your repository
    - uses: actions/checkout@v3
    - name: Scan IaC with Tenable Cloud Security
      uses: tenable/cloud-security-actions/iac/scan@v1
      with:
        api-token: ${{ secrets.TENABLE_API_TOKEN }}
        api-url: https://uk.app.ermetic.com
